### ISSUE TITLE
Unable to build docs when running grunt

### ISSUE THREAD

**Issue by davidpaulrosser** [Polymer/docs#1486]
I've followed all the instructions down to running ```grunt``` when doing so I receive this error. Do you guys know why?

```
Allow dev_appserver to check for updates on startup? (Y/n): Traceback (most recent call last):
  File "/usr/local/bin/dev_appserver.py", line 83, in <module>
    _run_file(__file__, globals())
  File "/usr/local/bin/dev_appserver.py", line 79, in _run_file
    execfile(_PATHS.script_file(script_name), globals_)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 1040, in <module>
    main()
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 1033, in main
    dev_server.start(options)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 771, in start
    update_checker.check_for_updates(configuration)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/devappserver2/update_checker.py", line 91, in check_for_updates
    if update_check.AllowedToCheckForUpdates():
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/sdk_update_checker.py", line 408, in AllowedToCheckForUpdates
    answer = input_fn('Allow dev_appserver to check for updates on startup? '
EOFError: EOF when reading a line
`bundle exec jekyll build --watch` was initiated.

Warning: Task "appengine:run:frontend" failed. Use --force to continue.

Aborted due to warnings.
    Warning:  Use --force to continue.
        
        Aborted due to warnings.
```

**Comment by davidpaulrosser** [comment]
Figured it out, I ran the dev_appserver once to complete the 'check for updates on startup'. Running grunt after worked fine. Maybe include this in your setup docs though.
