### ISSUE TITLE
Wrong versioning for test-fixture in hybrid elements guide?

### ISSUE THREAD

**Issue by juniperbelmont** [Polymer/docs#1941]
Not sure if this is an issue for others or just for me, but when I try to follow the steps at the bottom of the [hybrid elements page](https://www.polymer-project.org/2.0/docs/devguide/hybrid-elements), I get an error.

(I've substituted my project's path with `project_dir`)
```
$ polymer install --variants --verbose
[ ... ]
error:   cli runtime exception: test-fixture: Unable to find suitable version for test-fixture
error:   test-fixture: Unable to find suitable version for test-fixture
    at createError (/project_dir/node_modules/bower/lib/util/createError.js:4:15)
    at Manager._electSuitable (project_dir/node_modules/bower/lib/core/Manager.js:825:15)
    at project_dir/node_modules/bower/lib/core/Manager.js:609:25
    at _fulfilled (project_dir/node_modules/bower/lib/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (project_dir/node_modules/bower/lib/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (project_dir/node_modules/bower/lib/node_modules/q/q.js:796:13)
    at project_dir/node_modules/bower/lib/node_modules/q/q.js:556:49
    at runSingle (project_dir/node_modules/bower/lib/node_modules/q/q.js:137:13)
    at flush (project_dir/node_modules/bower/lib/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

This is the line that is giving me problems:
```    "test-fixture": "PolymerElements/test-fixture#>=1.0.0 <3.0.0", ```
It works if I change it to:
```    "test-fixture": "PolymerElements/test-fixture", ```

Also:
```
$ polymer --version
0.18.0-pre.13
```

**Comment by hguiney** [comment]
I get the same thing. Except it looks like `"test-fixture": "PolymerElements/test-fixture#>=1.0.0 <3.0.0",` is no longer in the docs. Now it has `"test-fixture": "PolymerElements/test-fixture#^2.0.0"`. I was also able to get it to work by taking off the version resolution though.

**Comment by arthurevans** [comment]
Sorry for the confusion. It appears that there's now a 3.0.0 version of test-fixture that should work with 2.x. For the 1.x variant, you should stick with ^1.0.0. Updated doc.
