### ISSUE TITLE
Host two projects failed

### ISSUE THREAD

**Issue by unbug** [Polymer/docs#767]
I was trying to host the EN version on my VPS,I already hosted the [CN](https://github.com/unbug/docs/tree/ZH).
I ran the CN version by use 

```
dev_appserver.py --port=3000 --host=0.0.0.0 . >GAE.log &

```

and run the EN version by use

```
dev_appserver.py --admin_port=8001 --port=3001 --host=0.0.0.0 . >polymeren.log &

```

Two servers were running,bug the second one can not be visited.
I got erros:

```
2014-11-20 14:23:46,352 sdk_update_checker.py:242] Checking for updates to the SDK.
WARNING  2014-11-20 14:23:46,501 api_server.py:383] Could not initialize images API; you are likely missing the Python "PIL" module.
INFO     2014-11-20 14:23:46,512 api_server.py:171] Starting API server at: http://localhost:48278
INFO     2014-11-20 14:23:48,944 dispatcher.py:182] Starting module "default" running at: http://0.0.0.0:3001
INFO     2014-11-20 14:23:48,946 admin_server.py:117] Starting admin server at: http://localhost:8001
OperationalError('database is locked',)
Traceback (most recent call last):
  File "/home/google_appengine/lib/cherrypy/cherrypy/wsgiserver/wsgiserver2.py", line 1302, in communicate
    req.respond()
  File "/home/google_appengine/lib/cherrypy/cherrypy/wsgiserver/wsgiserver2.py", line 831, in respond
    self.server.gateway(self).respond()
  File "/home/google_appengine/lib/cherrypy/cherrypy/wsgiserver/wsgiserver2.py", line 2115, in respond
    response = self.req.server.wsgi_app(self.env, self.start_response)
  File "/home/google_appengine/google/appengine/tools/devappserver2/wsgi_server.py", line 266, in __call__
    return app(environ, start_response)
  File "/home/google_appengine/google/appengine/tools/devappserver2/module.py", line 1408, in __call__
    return self._handle_request(environ, start_response)
  File "/home/google_appengine/google/appengine/tools/devappserver2/module.py", line 622, in _handle_request
    module=self._module_configuration.module_name)
  File "/home/google_appengine/google/appengine/api/apiproxy_stub.py", line 165, in WrappedMethod
    return method(self, *args, **kwargs)
  File "/home/google_appengine/google/appengine/api/logservice/logservice_stub.py", line 172, in start_request
    host, start_time, method, resource, http_version, module))
OperationalError: database is locked
OperationalError('database is locked',)

```

Any suggestions?

**Comment by Robophil** [comment]
when i run grunt i get
executing: dev_appserver.py --port=3000 --host=0.0.0.0 .
Fatal error: spawn dev_appserver.py ENOENT
    Warning:  Use --force to continue.
        
        Aborted due to warnings.
